<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Numpy array .
arr = np.array([1,2,3,4,5,6])
print(f'One dimensional array : {arr} \n')

# converting a list to numpy array .
l= [1,2,3,4,5,6,7,8,9]
arr1 = np.array(l)
print(f'List into array : {arr1}\n')

''' Here in numpy the datatype of all elemnts are same that means if we try to  input strins and float value than the all the datatype will become strings or float .'''

# int to float
f=[1,2,3.14]
arr2= np.array(f)
print(f'Int to float : {arr2}\n')

# int to string
s=[3.25 , 1 , 'c']
arr3 = np.array(s)
print(f'int to string : {arr3}')



One dimensional array : [1 2 3 4 5 6] 

List into array : [1 2 3 4 5 6 7 8 9]

Int to float : [1.   2.   3.14]

int to string : ['3.25' '1' 'c']


# Matrices and vectors :

# Matrix :
1.   A matrix is a two-dimensional array.
2.   Shape: (m, n) → two dimensions.
3. Usage: Represents datasets, transformations, or coefficients in linear algebra.







# Vectors :
1.  A vector is a one-dimensional array.
2. Shape: (n) → only one dimension.
3. Usage: Represents data points, coefficients, or directions in ML.

In [ ]:
# Matrix

# Matrix : It is arrangement of elements in rows and columns .
l1=[[1,2,3] , [4,5,6] , [7,8,9]]
print(f'{l1} \n ')
''' Here you can notice that instead of looking like a matrix it's a 1-D So '''

np.array(l1)

''' Here you can see now that This list converted to numpy array is more like and array now . '''

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
 


' Here you can see now that This list converted to numpy array is more like and array now . '

# Array generation functions

There are multiple ways to generate an array in numpy such as :

In [ ]:
# 1. Using arange() {means arrange array} .

''' It's same as range function ( start : end : step ) '''
arr_1 = np.arange(1,11)
print(f'{arr_1} \n\n ')

# 2. Creating a Null matrix . {A matrix with only zeros (0)}

''' This means it will create a zero martix with 1 row and 6 coloumns. '''
arr_2 = np.zeros(6)
print(f'{arr_2} \n\n')

''' For creating a 2-D array we'll do : '''

arr_3 = np.zeros((4,5)) # Here we have to pass the 4 rows and 5 columns , so the order is ( rows , columns ) .
print(f'{arr_3} \n\n')


arr_4 = np.ones(5) # Same ass null matrix be have a martix of only one's (1).
print(f'{arr_4} \n\n')

arr_5=np.ones((5,6))
print(f'{arr_5} \n\n')

[ 1  2  3  4  5  6  7  8  9 10] 

 
[0. 0. 0. 0. 0. 0.] 


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 


[1. 1. 1. 1. 1.] 


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 




# Using Linspace

In [ ]:
array1 =np.linspace(1,2,3)
print(f'{array1} \n\n ')

## Basically the function linspace is used to Evenly sapce the numbers .
# as in the showed example we can see that in given parameter is (1,2,3)
# that means that the number 1 and 2 between 3 evenly spaced intervals .

[1.  1.5 2. ] 

 


# Random Generation Function .

In [ ]:
# As random Library is already in built in python so we can directly use it but
# Here I'm using the import function for formality and easy to understand.


# 1. Using 'rand' function .

import random
print(f'{np.random.rand(10)} \n\n')
# The output of this code is an vector , and all the values generated are in the range 0 to 1 .
# It follows the concept of normalization (Statistic) .


# 2. Using 'randn' function .
print(f'{np.random.randn(10)} \n\n')
# it generates number in between -3 to 3 .
# the 'randn' function works on the concept of standardization (Statistic) .


# 3. Using 'raandint' function .
print(f'{np.random.randint(10, 15 , 20)}')
# Here the 'randint' function generates number between 10 to 15 , and it will generate 20 number Randomly between those two number.

[0.97076472 0.96220327 0.21573892 0.25396492 0.08231817 0.34338
 0.94518863 0.67517461 0.87332582 0.79044384] 


[-1.96065383  0.25211979  1.71696089 -0.42944199  0.41770715 -1.06280477
 -0.33676677  1.2714715   0.35917596  0.07742375] 


[12 12 11 13 12 13 13 11 12 10 14 10 12 11 10 12 12 14 13 12]


# Array Attribute

In [ ]:
# 1. shape

# It display's the shape of the array like 3x3  or 4x6 .
array_1 = np.array(
  [ [1,2,3],
    [4,5,6],
    [7,8,9] ]
)
print(f'Shape of the array : {array_1.shape} \n ')


# 2. Size
# It display's the total number of the elements in the array .

print(f'Size of the array : {array_1.size}\n')


# 3. dtype
# It display's the datatype of the array .

print(f'Datatype of the array : {array_1.dtype}')

Shape of the array : (3, 3) 
 
Size of the array : 9

Datatype of the array : int64


# Array Method

In [ ]:
array_0= np.array([[11,12,13],[14,15,16],[17,18,19]])
# 1. min()
# These function or method is used to find the minimum value of the numpy array .
print(f'The minimum value of array : {array_0.min()}')

#2. max()
# These method or function allows to find the maximun value of the numpy array .
print(f'The maximum value of the array : {array_0.max()}\n\n')

#3. sum()
# These method display's the grand total of the numpy array .
print(f'The total of the elements : {array_0.sum()}')

# One more thing , what if I have to do the sum of the first column only ?
# In that case we can some of the parameter to sum() method .

print(f'The total of each column : {array_0.sum(axis=0)}\n')
#             OR
print(f'The total of the first column : {array_0[:,0].sum()}')
print(f'The total of the second column : {array_0[:,1].sum()}')
print(f'The total of the third column : {array_0[:,2].sum()}\n\n')

#4. mean()
# It returns the mean of all the elements of the numpy array .
print(f'The mean of the array : {array_0.mean():.2f}')

#5. std()
# This method returns the standred deviation of the elements in the numpy array.
print(f'The standred deviation of the array : {array_0.std():.2f}\n')

#6. argmax() and argmin()
#   argmax() : It returns the index of the maximum value in the numpy array.
#   argmin() : It returns the index of the minimum value in the numpy array.

print(f'The index of the maximum value :{array_0.argmax()}')
print(f'The index of the minimum value :{array_0.argmin()}\n\n')

The minimum value of array : 11
The maximum value of the array : 19


The total of the elements : 135
The total of each column : [42 45 48]

The total of the first column : 42
The total of the second column : 45
The total of the third column : 48


The mean of the array : 15.00
The standred deviation of the array : 2.58

The index of the maximum value :8
The index of the minimum value :0




#Reshaping and Resizing

In [ ]:
# Here I have created a numpy array using arange() .
array_2= np.arange(1,31)
print(f'{array_2} \n')


# 1. reshape()
##> If I want to converrt this 1-D matrix to 2-D , we can do it using resahpe() method .
##> Here in the reshape we have to pass 2 parameters column and rows , like array.reshape(column , rows)
##? Here an error can occur as the given numpy matrix can't be converted to desired shape , because of unavalibility of the elements.
print(array_2.reshape(6,5))

# 2. Resize
##> When we store the reshaped numpy array that is reshaping .


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


#Indexing and Slicing


#Numpy Indexing and slicing of vectors

In [ ]:
a1 = np.arange(11,21)
print(f'{a1}\n')

# Indexing with vectors
##> Indexing means to call the value of the numpy array but it's index .
##> It's just like the indxing we use to do with lists .

print(f'Element at index zero : {a1[0]}\n')
##> like that we can use the indexing .
##? Don't give an index out of lenght of the array , because it will raise an "IndexError" .


# Slicing with vector
##> Slicing is a way to extract a portion (or "slice") of a sequence .
##> Syntax : name_of_array[start point : end point : step size ]

print(f'Slicing elements form 1 to 5 : {a1[1:6]} \n')
print(f'Slicing all elements form start to end : {a1[:]}\n')
print(f'Slicing elements form a specific index to end :{a1[6:]} \n')
print(f'Slicing elements with a specific step size : {a1[::2]} \n')

[11 12 13 14 15 16 17 18 19 20]

Element at index zero : 11

Slicing elements form 1 to 5 : [12 13 14 15 16] 

Slicing all elements form start to end : [11 12 13 14 15 16 17 18 19 20]

Slicing elements form a specific index to end :[17 18 19 20] 

Slicing elements with a specific step size : [11 13 15 17 19] 



#Numpy Indexing and slicing of Matrix

In [ ]:
a2= np.arange(1,31).reshape(6,5)
print(f'{a2} \n')

# Indexing in numpy array .
##> In 2-D array to acess any elemet we have to give the row and column index .
##> Like if I only gave row or column index the this would happen :

print(f'Slicing a row (2) :\n {a2[2]} \n')
print(f'Slicing a cloumn : \n {a2[:,:1]} \n')


##> If I want to target a specific element of then we have to give both the row and the column number .
print(f'Indexing through Slicing :\n {a2[5,4]} \n ')

##? What if I want to slice out 2 , 3 , 7 and 8 out this matrix ?
##> We can do it as :
print(f'Slicing a portion out of Matrix : \n{a2[0:2,1:3]} \n')
print(f'Another example : \n{a2[3:,3:]}\n')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

Slicing a row (2) :
 [11 12 13 14 15] 

Slicing a cloumn : 
 [[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]] 

Indexing through Slicing :
 30 
 
Slicing a portion out of Matrix : 
[[2 3]
 [7 8]] 

Another example : 
[[19 20]
 [24 25]
 [29 30]]



#Boolean Indexing

It allows to filter or select elements from an array based on a condition rather than their numeric indices.

In [ ]:
a3=np.arange(1,11)
print(f'\n{a3}\n')

##> Boolean indexing is used as :
bool_index = a3 % 2 ==0


##> When you apply a condition to a NumPy array or vector,
# the condition is evaluated for every individual element.
print(f'{bool_index}\n')

##> ANd if we returned our bool_index array to our original array,
# we get the elements which corresponds to 'TRUE' boolean value as per our condition .
print(f'{a3[bool_index]}\n')


[ 1  2  3  4  5  6  7  8  9 10]

[False  True False  True False  True False  True False  True]

[ 2  4  6  8 10]



#Array Operations


##1. Arithmatic operations

In [ ]:
#Creating 2 numpy vector's .
v1=np.arange(1,10)
v2=np.arange(11,20)

print(f'First vector : \n{v1}\n')
print(f'Second vector : \n{v2}\n')

##> 1. Addition of two vector  .
# The addition of vectors is same as the addition of 2 variables ; like a+b = c
# like that :
print(f'Addition of two vector : \n{v1+v2}\n')

##> And just like we can also substract it .
print(f'Substraction of two vector : \n{v1-v2}\n')

##> Same of the multiplication :
print(f'Multiplication of two vector : \n{v1*v2}\n')

##> And division :
print(f'Division of two vector : \n{v1/v2}\n')

##> And floor division :
print(f'Floor division of two vector : \n{v1//v2}\n')

##> And Exponent :
print(f'Exponential of two vector : \n{v1**v2}\n')

##> And Modulus :
print(f'Modulus of two vector : \n{v1%v2}\n')

##? Here an important thing to mark is that we have to keep the order of both numpy vectors the same .
#   Otherwise it will raise the error : ValueError .

First vector : 
[1 2 3 4 5 6 7 8 9]

Second vector : 
[11 12 13 14 15 16 17 18 19]

Addition of two vector : 
[12 14 16 18 20 22 24 26 28]

Substraction of two vector : 
[-10 -10 -10 -10 -10 -10 -10 -10 -10]

Multiplication of two vector : 
[ 11  24  39  56  75  96 119 144 171]

Division of two vector : 
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]

Floor division of two vector : 
[0 0 0 0 0 0 0 0 0]

Exponential of two vector : 
[                  1                4096             1594323
           268435456         30517578125       2821109907456
     232630513987207   18014398509481984 1350851717672992089]

Modulus of two vector : 
[1 2 3 4 5 6 7 8 9]



In [ ]:
## Creating 2 matrices
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)

print(f'First array :  \n{m1}\n')
print(f'Second array : \n{m2}\n\n')


##> Arithmatic operations on Matrices ,
#> Addition
print(f'Addition of the matrices is : \n{m1+m2}\n')

#>Substraction
print(f'Substraction of the matrices is : \n{m1-m2}\n')

#> Multiplication
##> This multiplication is a direct multiplication , means it dosen't mutiply
#   Like rows  x cloumns , instead it directly multipliy the corresponding elements .
print(f'Multiplication of two array is : \n{m1*m2}\n')

#> Division
print(f'Division of two array is : \n{m1/m2}\n')

#> Floor Division
print(f'Floor Division of two array is : \n{m1//m2}\n')

#> Exponential
print(f'Exponential of two array is : \n{m1**m2}\n')

#> Modulus
print(f'Modulus of two array is : \n{m1%m2}\n')

##? Here an important thing to mark is that we have to keep the order of both numpy matrices the same .
#   Otherwise it will raise the error : ValueError .

First array :  
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array : 
[[11 12 13]
 [14 15 16]
 [17 18 19]]


Addition of the matrices is : 
[[12 14 16]
 [18 20 22]
 [24 26 28]]

Substraction of the matrices is : 
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]

Multiplication of two array is : 
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]

Division of two array is : 
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]

Floor Division of two array is : 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Exponential of two array is : 
[[                  1                4096             1594323]
 [          268435456         30517578125       2821109907456]
 [    232630513987207   18014398509481984 1350851717672992089]]

Modulus of two array is : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]



#Deep and Shallow Copy

In [ ]:
## DEEP COPY
##> To understand the concept of deep copy, let us consider an example :
# Let us create a vector :
v3=np.arange(1,10)
print(f'{v3}')

# And now let us silce the this vector
s = v3[:6]
print(s+10)

##> As you can see that we have done some changes in the vector .
#   Does that affect the original vector . Let's check it by printing the numpy vector in the next cell .

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16]


In [ ]:
print(v3)

##> As you can see that the numpy vector has not being changed at all.
#  This is the concept of Shallow copy , it means that the silced part has created a seprate memeory space in the RAM (Random Acess Memory).
#  It means that the changes made in this part would not affect the original numpy vector .
#  Because the silce variable is not targeting the memeory location on the numpy vector .

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Deep copy
##> Opposite to the shallow copy , means if we make changes in the numpy array  in any way it would be reflected in the original numpy vector .
#   Like for example:
v4=np.arange(20,30)
print(f'{v4}')

# Now lets us keep is v4 vector in some other variable .
V = v4

# And now if we make cjhanges in the vector :

V[5]=56
print(f'\n{V}\n')

# Here as you can see that there is change in the element in the vector .
# Does that meant there is a change in the original vector too ?
print(f'\n{v4}\n')

##> As you can clearly see that there are changes in the original vector .
##> And this is the concept on deep copy .
#   In deep copy the memory address or location is of one varible is targeted by both variable ,
#   that mean if we change anything in one variable that change will apper in    another variable.

[20 21 22 23 24 25 26 27 28 29]

[20 21 22 23 24 56 26 27 28 29]


[20 21 22 23 24 56 26 27 28 29]



In [ ]:
##? But if we want to store a numpy array or vector in some another variable    and we dont want to be changed .
#   Then we can simply create it's copy . Like :
V1=v4.copy()
print(f'{v4}')


# And if we change something :
V1[6] = 99
print(f'\n{V1}\n')
print(f'{v4}\n')

##> As you can see that now if change anything There is no effect in original numpy array or vector

[20 21 22 23 24 56 26 27 28 29]

[20 21 22 23 24 56 99 27 28 29]

[20 21 22 23 24 56 26 27 28 29]



#Matrix operations

In [ ]:
mat1=np.arange(1,5).reshape(2,2)
mat2=np.arange(5,9).reshape(2,2)

# Now our first opeartion is , matrix multiplication

''''''
# 1.Dot product

##> As we have seen above some of arithmetic operation that we can multiply the matrices or vectors simply putting a multiplication symbol in between them .
#   But that multiplication was index wise multiplication not actual matrix multiplication
#   So for that we can do :

multiply1= mat1 @ mat2
print(f'Matrix multiplication : \n{multiply1}\n')

# Another way to do that is :
multiply2= mat1.dot(mat2)
print(f'Matrix multiplication : \n{multiply2}\n')

# Transpose of matrix
transpose1=mat1.transpose()
print(f'Transpose of matrix : \n{transpose1}\n')

# Or
transpose2=mat1.T
print(f'Transpose of matrix : \n{transpose2}\n')

# Inverse of matrix
inverse1=np.linalg.inv(mat1)
print(f'Inverse of matrix : \n{inverse1}\n')



Matrix multiplication : 
[[19 22]
 [43 50]]

Matrix multiplication : 
[[19 22]
 [43 50]]

Transpose of matrix : 
[[1 3]
 [2 4]]

Transpose of matrix : 
[[1 3]
 [2 4]]

Inverse of matrix : 
[[-2.   1. ]
 [ 1.5 -0.5]]



# Advance array operation

###Stacking operation

In [ ]:
# Stacking :
##> stacking means to join two or more numpy vectors .
#   we cannot stack matrices because they aare already stacked .
# Lets create 2 vectors :
vec1=np.arange(1,5)
vec2=np.arange(5,9)
print(f'Vector 1 : {vec1}\n')
print(f'Vector 2 : {vec2}\n')

# 1. Vertical stack
print(f'Vertical stack :\n {np.vstack((vec1,vec2))}\n')

# 2. Horizontal stack
print(f'Horizontal stack : \n{np.hstack((vec1,vec2))}\n')

# 3.Column stack
print(f'Column stack : \n{np.column_stack((vec1,vec2))}\n')



Vector 1 : [1 2 3 4]

Vector 2 : [5 6 7 8]

Vertical stack :
 [[1 2 3 4]
 [5 6 7 8]]

Horizontal stack : 
[1 2 3 4 5 6 7 8]

Column stack : 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]



#Spliting opeartion

In [ ]:
# Spliting
##> Splitting means to disjoint or break a an array in equal divisions  .
# For example:

splitting1=np.arange(1,10).reshape(3,3)
print(f'{splitting1}\n')

# 1. Horizontal split :
print(f'Horizontal split : \n{np.hsplit(splitting1,3)}\n')

# 2. Vertical split :
print(f'Vertical split : \n{np.vsplit(splitting1,3)}\n')

##> For better prsentaion :
for i in np.hsplit(splitting1,3):
  print(i , "\n")

for j in np.vsplit(splitting1,3):
  print(j,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal split : 
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

Vertical split : 
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

[[1]
 [4]
 [7]] 

[[2]
 [5]
 [8]] 

[[3]
 [6]
 [9]] 

[[1 2 3]] 

[[4 5 6]] 

[[7 8 9]] 



#Exercises

###Valid sudoku

##### Q1. You are given a sudoku your task is to validate the following:


1.   Validate the sum for each row .
2.   Validate the sum for each column.
3.   Where did the sum each 3X3 block.


In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
print(s)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [ ]:
# Q1. Sum of each row ?

##> My approch .
for i in s[0:,0:]:
  print(f'Sum of each row : {i} = {i.sum()}')

print("\n")

##> Correct approch :
z=np.sum(s,axis=1)
print(z)

#checking condition .
#

#or
for i in z:
  if i!=45:
    print("invaild sudoku")
    break
else:
  print("for rows the vaild sudoku")

Sum of each row : [5 3 4 6 7 8 9 1 2] = 45
Sum of each row : [6 7 2 1 9 5 3 4 8] = 45
Sum of each row : [1 9 8 3 4 2 5 6 7] = 45
Sum of each row : [8 5 9 7 6 1 4 2 3] = 45
Sum of each row : [4 2 6 8 5 3 7 9 1] = 45
Sum of each row : [7 1 3 9 2 4 8 5 6] = 45
Sum of each row : [9 6 1 5 3 7 2 8 4] = 45
Sum of each row : [2 8 7 4 1 9 6 3 5] = 45
Sum of each row : [3 4 5 2 8 6 1 7 9] = 45


[45 45 45 45 45 45 45 45 45]
for rows the vaild sudoku


In [ ]:
# Q2. Sum of each column ?

##> My approch .
q= np.sum(s,axis=0)
print(f'The sum of the column is : {q}\n')

for j in q:
  if j !=45:
    print("invaild sudoku")
    break
else:
  print("for columns the vaild sudoku")

##> This approch is correct .

The sum of the column is : [45 45 45 45 45 45 45 45 45]

for columns the vaild sudoku


In [ ]:
# Q3. Check the validity of each block .

##>My approch.
print(f' sum of first block : {np.sum(s[0:3,0:3])}')
# so this will print the sum of the first block of sudoku .
# here I have noticed that the rows remains the same only the column are changing . SO :
for i in range(0,9,3):
  for j in range(0,9,3):
    print(f'Sum of block \n {s[i:i+3,j:j+3]}: {np.sum(s[i:i+3,j:j+3])}\n')


# This is a correct approch .

 sum of first block : 45
Sum of block 
 [[5 3 4]
 [6 7 2]
 [1 9 8]]: 45

Sum of block 
 [[6 7 8]
 [1 9 5]
 [3 4 2]]: 45

Sum of block 
 [[9 1 2]
 [3 4 8]
 [5 6 7]]: 45

Sum of block 
 [[8 5 9]
 [4 2 6]
 [7 1 3]]: 45

Sum of block 
 [[7 6 1]
 [8 5 3]
 [9 2 4]]: 45

Sum of block 
 [[4 2 3]
 [7 9 1]
 [8 5 6]]: 45

Sum of block 
 [[9 6 1]
 [2 8 7]
 [3 4 5]]: 45

Sum of block 
 [[5 3 7]
 [4 1 9]
 [2 8 6]]: 45

Sum of block 
 [[2 8 4]
 [6 3 5]
 [1 7 9]]: 45



#Student matrix

Q2. You are given two dimensional matrix of student data.


1.   Get the shape of the matrix.
2.   Find the average of age of the student.
3.   Extract Math marks of all the student .
4.   Find the highest marks scored in Science .
5.   Get the details of the student who scored more than 90 marks in Math .
6.   Increase Math marks of all students by 5.
7.   Find how many students are younger than 19.
8.   Calculate the average marks in each subject (column-wise mean).
9.   Get data of students who scored at least 80 in both subjects.
10.  Replace all Science marks < 75 with 0.

In [ ]:
# The given matrix :

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#1. Get the shape of the matrix.

##> My approch.
print(f'The shape of the matrix : {np.shape(data)}')

##> This is a vaild approch .

The shape of the matrix : (5, 3)


In [ ]:
# 2. Find the average of age of the student.

##> My approch .
print(f'The average of age of the student : {np.mean(data[:,0])}')

##> This is a correct approch.

The average of age of the student : 18.4


In [ ]:
# 3. Extract Math marks of all the student .
print(f'Math marks of all the student : {data[:,1]}')

##> This is a correct approch.

Math marks of all the student : [85 92 76 65 90]


In [ ]:
# 4. Find the highest marks scored in Science .

##> My Approch
print(f'Highest marks in Science : {np.max(data[:,2])}')

##> This is a correct approch .

Highest marks in Science : 95


In [ ]:
# 5. Get the details of the student who scored more than 90 marks in Math .

##> My Approch .
# Here we ca use boolean operation by giving a condition of marks > 90 while slicing the Math marks.
# And to pick that entire section we'll use the indexing .
# So if we combine the both ofthem we'll get :

print(f'Details of the student who scored more than 90 marks in Math : \n{data[data[:,1]>90]}')

##> This is a correct approch .

Details of the student who scored more than 90 marks in Math : 
[[19 92 88]]


In [ ]:
# 6. Increase Math marks of all students by 5.
##> My approch .

# As we know that numpy allows broadcasting so if I extaract the math's marks by silcing.
# ad then add 5 to them the entire extracted element(math's marks) will be increased by 5.
# SO ,
print(f"Actual Math's marks : \n{data[:,1]}\n")
print(f"Math's Marks incresed by 5: \n{data[:,1]+5}")

##> This is a correct approch .

Actual Math's marks : 
[85 92 76 65 90]

Math's Marks incresed by 5: 
[90 97 81 70 95]


In [ ]:
# 7. Find how many students are younger than 19.
print(f' The students below 19 :\n{data[data[0:]<19]}')

 The students below 19 :
[18 17 18]


In [ ]:
# 8. Calculate the average marks in each subject (column-wise mean).

print(f'Average marks in Math : {np.mean(data[:,1])}')
print(f"Average marks in Science : {np.mean(data[:,2])}")

Average marks in Math : 81.6
Average marks in Science : 83.2


In [ ]:
# 9. Get data of students who scored at least 80 in both subjects.

##> My approch
# In order to extract the data of the student who has scored more than 80 in both Math and Science.
# We need to to extract both Math & science marks columns and apply conditions on them .
# Also we have to pick the marks above 80 seperately form both the columns and check wheather they are true by bitwise 'and'.

print(f"student's data who scored at least 80 in both subjects : \n{data[data[:,1]>80] & data[data[:,2]>80] }")

##> This is a correct approch .

student's data who scored at least 80 in both subjects : 
[[18 84 72]
 [17 76 88]
 [20 90 85]]


In [ ]:
# I brought the data matrix here so that I can see the matrix :
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


In [ ]:
# 10 .Replace all Science marks < 75 with 0

# My approch :
# First I have to target the Science Mark column then apply condition on them boolean operations and then set those index to zero by Assignment operator .

# Create a boolean mask where Science marks are less than 75
condition = data[:, 2] < 75

# Apply the condition to the Science marks column and replace values with 0
data[condition, 2] = 0

print(f"Matrix after replacing Science marks < 75 with 0:\n{data}")

Matrix after replacing Science marks < 75 with 0:
[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]


Here , I think I have completed my numpy and I'll make a small project on my understanding of numpy in my next numpy project repo .

#SOME MORE QUESTIONS

###1.Chessboard

Create an 8 X 8 chessboard using NumPy where:
*   White squares = 0
*   Black squares = 1


In [ ]:
##> My approch
# I'll create a numpy array of zeroes .
# And he I'll traverse through the array by silcing .
# Then I'll put the condiion and convert the alternative positios to 1 .

board = np.zeros((8,8),dtype=int)
board[1::2,::2]=1
board[::2,1::2]=1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Q2. Border of Ones

Create a 6×6 matrix of zeros.

Change only the border elements to 1.

In [ ]:
##> My approch
# first I'll create a upy array of zeroes ,
# then I'll target the first and last rows and columns.
# Then through slicing I'll get there index and give them a new value .

matrix=np.zeros((6,6) , dtype = int)
print(matrix)

print("\n")

matrix[0:1]=1
matrix[5:6]=1
matrix[:,0:1]=1
matrix[:,5:6]=1

print(matrix)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#Q3. Reverse Every Row

Given

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

Output

[[3 2 1]
 [6 5 4]
 [9 8 7]]

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
temp=0
for i in arr:
  temp=i[0]
  i[0]=i[2]
  i[2]=temp
  print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 2 1]
[6 5 4]
[9 8 7]


# Q4. Replace Negatives

Given

arr = np.array([2,-5,7,-9,1,-2,4])

Replace every negative value with 0.

In [ ]:
p=np.array([2,-5,7,-9,-2,4])
print(p)

p[p<0]=0
p

[ 2 -5  7 -9 -2  4]


array([2, 0, 7, 0, 0, 4])

#Q5 Student Marks Analysis
1. Print the total marks of each student.
2. Print the average marks of each student.
3. Find the student with the highest total marks.
4. Find the average marks of each subject.
5. Find the topper of each subject.
6. Count how many students scored above 80 in each subject.
7. Print the overall class average.

In [ ]:
# Given
marks = np.array([
    [85, 90, 78],
    [75, 88, 92],
    [60, 70, 65],
    [95, 98, 99],
    [80, 85, 88]
])

##> 1. Print the total marks of each student.
print(f'Total marks of each student : \n{marks.sum(axis=0)}\n')

##> 2. Print the average marks of each student.
print(f'Average marks of each student : \n{marks[0:].mean(axis=1)}\n')

##> 3. Find the student with the highest total marks.
print(f'Student with highest total marks : {np.max(marks)}\n')

##> 4. Find the average marks of each subject.
print(f'Average of each subject : {np.mean(marks,axis=0)}\n')

##> 5. Find the topper of each subject.
print(f'Topper of each subject : {np.max(marks, axis=0)}\n')

##> 6. Count how many students scored above 80 in each subject.
print(f'Total number of student who scored more than 80 in each subject  :{len(marks[marks[:] > 80 ])}\n')

##> 7. Print the overall class average.
print(f'Overall class average : {np.average(marks , axis = 0)}')

Total marks of each student : 
[395 431 422]

Average marks of each student : 
[84.33333333 85.         65.         97.33333333 84.33333333]

Student with highest total marks : 99

Average of each subject : [79.  86.2 84.4]

Topper of each subject : [95 98 99]

Total number of student who scored more than 80 in each subject  :9

Overall class average : [79.  86.2 84.4]


#Q6 Image Processing
1. Increase brightness by 30.
2. If any pixel becomes greater than 255, make it 255.
3. Decrease brightness by 50.
4. If any value becomes negative, make it 0.
5. Find the brightest pixel.
6. Find the darkest pixel.
7. Calculate the average brightness of the image.

In [2]:
# Given
img = np.array([
    [120,130,125],
    [110,140,135],
    [150,160,170]
])

##> 1. Increase brightness by 30.
print(f'Increased by 30:\n {img +30}')

##>2. If any pixel becomes greater than 255, make it 255.
img[img[:]>255]=0
print(f'If any pixel becomes greater than 255, make it 255:\n {img}\n')

##> 3. Decrease brightness by 50.
print(f'Decreased brightness by 50  :\n{img-50}\n')

##> 4. If any value becomes negative, make it 0.
img[img[:]<0]=0
print(f'Converting negative value to zero : \n{img}\n')


##> 5. Find the brightest pixel.
print(f'Brightest pixel :{np.max(img)}')

##> 6. Find the darkest pixel.
print(f'Darkest pixel : {np.min(img)}\n')

##> 7. Calculate the average brightness of the image.
print(f'Average brightness : {np.average(img):.2f}\n')

Increased by 30:
 [[150 160 155]
 [140 170 165]
 [180 190 200]]
If any pixel becomes greater than 255, make it 255:
 [[120 130 125]
 [110 140 135]
 [150 160 170]]

Decreased brightness by 50  :
[[ 70  80  75]
 [ 60  90  85]
 [100 110 120]]

Converting negative value to zero : 
[[120 130 125]
 [110 140 135]
 [150 160 170]]

Brightest pixel :170
Darkest pixel : 110

Average brightness : 137.78

