<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Numpy array .
arr = np.array([1,2,3,4,5,6])
print(arr)

# converting a list to numpy array .
l= [1,2,3,4,5,6,7,8,9]
arr1 = np.array(l)

''' Here in numpy the datatype of all elemnts are same that means if we try to  input strins and float value than the all the datatype will become strings or float .'''

# int to float
f=[1,2,3.14]
arr2= np.array(f)

# int to string
s=[3.25 , 1 , 'c']
arr3 = np.array(s)

print(f'{arr1} \n{arr2} \n{arr3}')

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9] 
[1.   2.   3.14] 
['3.25' '1' 'c']


In [ ]:
# Matrix

# Matrix : It is arrangement of elements in rows and columns .
l=[[1,2,3] , [4,5,6] , [7,8,9]]
print(f'{l} \n ')
''' Here you can notice that instead of looking like a matrix it's a 1-D So '''

np.array(l)

''' Here you can see now that This list converted to numpy array is more like and array now . '''

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
 


' Here you can see now that This list converted to numpy array is more like and array now . '

# Array generation functions

There are multiple ways to generate an array in numpy such as :

In [ ]:
# 1. Using arange() {means arrange array} .

''' It's same as range function ( start : end : step ) '''
arr_1 = np.arange(1,11)
print(f'{arr_1} \n\n ')

# 2. Creating a Null matrix . {A matrix with only zeros (0)}

''' This means it will create a zero martix with 1 row and 6 coloumns. '''
arr_2 = np.zeros(6)
print(f'{arr_2} \n\n')

''' For creating a 2-D array we'll do : '''

arr_3 = np.zeros((4,5)) # Here we have to pass the 4 rows and 5 columns , so the order is ( rows , columns ) .
print(f'{arr_3} \n\n')


arr_4 = np.ones(5) # Same ass null matrix be have a martix of only one's (1).
print(f'{arr_4} \n\n')

arr_5=np.ones((5,6))
print(f'{arr_5} \n\n')

[ 1  2  3  4  5  6  7  8  9 10] 

 
[0. 0. 0. 0. 0. 0.] 


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 


[1. 1. 1. 1. 1.] 


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 




# Using Linspace

In [ ]:
array1 =np.linspace(1,2,3)
print(f'{array1} \n\n ')

## Basically the function linspace is used to Evenly sapce the numbers .
# as in the showed example we can see that in given parameter is (1,2,3)
# that means that the number 1 and 2 between 3 evenly spaced intervals .

[1.  1.5 2. ] 

 


# Random Generation Function .

In [ ]:
np.random.rand(10)

array([0.72555581, 0.46885565, 0.52061024, 0.81334105, 0.83817092,
       0.63439482, 0.30211327, 0.93990428, 0.54926982, 0.70758069])