<a href="https://colab.research.google.com/github/Adityadevhare/ML-learning-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
# Numpy array .
arr = np.array([1,2,3,4,5,6])
print(f'One dimensional array : {arr} \n')

# converting a list to numpy array .
l= [1,2,3,4,5,6,7,8,9]
arr1 = np.array(l)
print(f'List into array : {arr1}\n')

''' Here in numpy the datatype of all elemnts are same that means if we try to  input strins and float value than the all the datatype will become strings or float .'''

# int to float
f=[1,2,3.14]
arr2= np.array(f)
print(f'Int to float : {arr2}\n')

# int to string
s=[3.25 , 1 , 'c']
arr3 = np.array(s)
print(f'int to string : {arr3}')



One dimensional array : [1 2 3 4 5 6] 

List into array : [1 2 3 4 5 6 7 8 9]

Int to float : [1.   2.   3.14]

int to string : ['3.25' '1' 'c']


# Matrices and vectors :

# Matrix :
1.   A matrix is a two-dimensional array.
2.   Shape: (m, n) → two dimensions.
3. Usage: Represents datasets, transformations, or coefficients in linear algebra.







# Vectors :
1.  A vector is a one-dimensional array.
2. Shape: (n) → only one dimension.
3. Usage: Represents data points, coefficients, or directions in ML.

In [19]:
# Matrix

# Matrix : It is arrangement of elements in rows and columns .
l1=[[1,2,3] , [4,5,6] , [7,8,9]]
print(f'{l1} \n ')
''' Here you can notice that instead of looking like a matrix it's a 1-D So '''

np.array(l1)

''' Here you can see now that This list converted to numpy array is more like and array now . '''

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
 


' Here you can see now that This list converted to numpy array is more like and array now . '

# Array generation functions

There are multiple ways to generate an array in numpy such as :

In [ ]:
# 1. Using arange() {means arrange array} .

''' It's same as range function ( start : end : step ) '''
arr_1 = np.arange(1,11)
print(f'{arr_1} \n\n ')

# 2. Creating a Null matrix . {A matrix with only zeros (0)}

''' This means it will create a zero martix with 1 row and 6 coloumns. '''
arr_2 = np.zeros(6)
print(f'{arr_2} \n\n')

''' For creating a 2-D array we'll do : '''

arr_3 = np.zeros((4,5)) # Here we have to pass the 4 rows and 5 columns , so the order is ( rows , columns ) .
print(f'{arr_3} \n\n')


arr_4 = np.ones(5) # Same ass null matrix be have a martix of only one's (1).
print(f'{arr_4} \n\n')

arr_5=np.ones((5,6))
print(f'{arr_5} \n\n')

[ 1  2  3  4  5  6  7  8  9 10] 

 
[0. 0. 0. 0. 0. 0.] 


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 


[1. 1. 1. 1. 1.] 


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 




# Using Linspace

In [ ]:
array1 =np.linspace(1,2,3)
print(f'{array1} \n\n ')

## Basically the function linspace is used to Evenly sapce the numbers .
# as in the showed example we can see that in given parameter is (1,2,3)
# that means that the number 1 and 2 between 3 evenly spaced intervals .

[1.  1.5 2. ] 

 


# Random Generation Function .

In [18]:
# As random Library is already in built in python so we can directly use it but
# Here I'm using the import function for formality and easy to understand.


# 1. Using 'rand' function .

import random
print(f'{np.random.rand(10)} \n\n')
# The output of this cod is an vector , and all the values generated in range 0 to 1 .
# It follows the concept of normalization (Statistic) .


# 2. Using 'randn' function .
print(f'{np.random.randn(10)} \n\n')
# the 'randn' function works on the concept of standardization (Statistic) .


# 3. Using 'raandint' function .
print(f'{np.random.randint(10, 15 , 20)}')
# Here the 'randint' function generates number between 10 to 15 , and it will generate 20 number Randomly between those two number.

[0.22821194 0.54813638 0.54222694 0.25395672 0.98800543 0.77761546
 0.09732103 0.7622925  0.44625887 0.48251283] 


[ 0.95243609 -0.19773704 -0.13275913  2.14569231  0.09494423  1.36470487
  0.43047616  1.55013362  0.34618966 -0.15245575] 


[13 10 11 11 10 11 14 13 14 11 11 12 14 10 14 13 12 14 13 13]


# Array Attribute

In [36]:
# 1. shape

# It display's the shape of the array like 3x3  or 4x6 .
array_1 = np.array(
  [ [1,2,3],
    [4,5,6],
    [7,8,9] ]
)
print(f'Shape of the array : {array_1.shape} \n ')


# 2. Size
# It display's the total number of the elements in the array .

print(f'SIze of the array : {array_1.size}\n')


# 3. dtype
# It display's the datatype of the array .

print(f'Datatype of the array : {array_1.dtype}')

Shape of the array : (3, 3) 
 
SIze of the array : 9

Datatype of the array : int64
